services:  
  mosquitto:  
    image: mosquitto_with_openssl
    container_name: mosquitto  
    restart: unless-stopped  
    volumes:  
      - ./mosquitto:/mosquitto  
      - ./mosquitto/data:/mosquitto/data  
      - ./mosquitto/log:/mosquitto/log  
      - ./mosquitto/certs:/mosquitto/certs
    ports:  
      - 1883:1883
      - 8883:8883  
      - 9001:9001