alias: " Coffee power plug disable at 6pm."
description: ""
triggers:
  - trigger: time
    at: "18:00:00"
conditions:
  - condition: time
    weekday:
      - mon
      - tue
      - wed
      - thu
      - fri
actions:
  - type: turn_off
    device_id: DEVICE_ID_HERE
    entity_id: ENTITY_ID_HERE
    domain: switch
mode: single